# Veri ayarları
data:
  raw_path: "data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  processed_path: "data/processed/"
  test_size: 0.2
  random_state: 42

# Model ayarları
model:
  target_column: "Churn"
  
  logistic_regression:
    C: 1.0
    max_iter: 1000

  random_forest:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 5

  xgboost:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8

# MLflow ayarları
mlflow:
  experiment_name: "telco-churn"
  tracking_uri: "mlruns"
